### ISSUE TITLE
vagrant hostmanager should remove duplicate hostnames/aliases in /etc/hosts of the host machine

### ISSUE THREAD

**Issue by datphan** [teracyhq-incubator/teracy-dev-essential#24]
When you have 2 VMs running with the same config, 2 hostnames/aliases will be mapped to difference IP , we should warn user and use the later VM's IP

**Comment by hoatle** [comment]
it's expected, you need to configure aliases for each VM, ref: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s/blob/develop/config_default.yaml#L50

**Comment by datphan** [comment]
I know:
1st VM is old iorad using teracy-dev 0.5
2nd VM is using new teracy-dev

`/etc/hosts` will look like this, after you `vagrant up`, `vagrant hostamanger` the 2nd VM
```
## vagrant-hostmanager-start id: 7ad31f5b-223b-4673-9f93-54d6f940a1ea <- old VM
192.168.1.88  dev.iorad.local
...
...
## vagrant-hostmanager-end

## vagrant-hostmanager-start id: <-- new VM
192.168.1.88  dev.iorad.local
...
...
## vagrant-hostmanager-end
```

what should we do about this case?

**Comment by hoatle** [comment]
in this case:
- vagrant destroy the 1st project to clean up existing domain aliases
- vagrant up the 2nd project

**Comment by hoatle** [comment]
`$ vagrant halt` the 1st project should work too

**Comment by datphan** [comment]
`vagrant destroy` works but not `vagrant halt`, but still we should have a warning message for debugging purpose

**Comment by hoatle** [comment]
I agree, we should check /etc/hosts for duplicated aliases and a warning to users is great to show them how to handle the situation.

**Comment by hoatle** [comment]
`$ vagrant halt && vagrant hostmanger` the 1st (old) project should help

**Comment by hoatle** [comment]
need to verify on Cygwin
